import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  safelist: [
    "bg-primary",
    "bg-primary/10",
    "bg-panel",
    "bg-panel/95",
    "bg-muted",
    "bg-muted-foreground",
    "bg-success",
    "bg-warning",
    "text-primary",
    "text-primary-foreground",
    "text-foreground",
    "text-muted-foreground",
    "text-success",
    "text-warning",
    "text-danger",
    "border-primary",
    "border-primary/25",
    "border-border",
    "border-danger",
    "border-danger/25",
    "border-success/25",
    "border-warning/25",
    "bg-success/10",
    "bg-warning/10",
    "bg-danger",
    "bg-danger/10",
    "bg-section-admin/10",
    "bg-section-collect/10",
    "bg-section-daily/10",
    "bg-section-governance/10",
    "bg-section-monitor/10",
    "bg-section-operate/10",
    "bg-section-platform/10",
    "bg-section-support/10",
    "border-section-admin/20",
    "border-section-collect/20",
    "border-section-daily/20",
    "border-section-governance/20",
    "border-section-monitor/20",
    "border-section-operate/20",
    "border-section-platform/20",
    "border-section-support/20",
    "text-section-admin",
    "text-section-collect",
    "text-section-daily",
    "text-section-governance",
    "text-section-monitor",
    "text-section-operate",
    "text-section-platform",
    "text-section-support",
    "hover:bg-primary/90",
    "hover:bg-muted",
    "hover:bg-muted/60",
    "hover:bg-danger/90",
    "hover:text-foreground",
    "focus-visible:ring-ring/35",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        panel: {
          DEFAULT: "hsl(var(--panel))",
          foreground: "hsl(var(--panel-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        success: "hsl(var(--success))",
        warning: "hsl(var(--warning))",
        danger: "hsl(var(--danger))",
        info: "hsl(var(--info))",
        section: {
          daily: "hsl(var(--section-daily))",
          collect: "hsl(var(--section-collect))",
          monitor: "hsl(var(--section-monitor))",
          operate: "hsl(var(--section-operate))",
          admin: "hsl(var(--section-admin))",
          support: "hsl(var(--section-support))",
          platform: "hsl(var(--section-platform))",
          governance: "hsl(var(--section-governance))",
        },
        /* Stitch / Material-3 design tokens (see app/globals.css). */
        "surface-bg": "hsl(var(--surface-bg))",
        "surface-container-lowest": "hsl(var(--surface-container-lowest))",
        "surface-container-low": "hsl(var(--surface-container-low))",
        "surface-container": "hsl(var(--surface-container))",
        "surface-container-high": "hsl(var(--surface-container-high))",
        "surface-container-highest": "hsl(var(--surface-container-highest))",
        "surface-variant": "hsl(var(--surface-variant))",
        "on-surface": "hsl(var(--on-surface))",
        "on-surface-variant": "hsl(var(--on-surface-variant))",
        outline: "hsl(var(--outline))",
        "outline-variant": "hsl(var(--outline-variant))",
        "border-subtle": "hsl(var(--border-subtle))",
        "on-primary": "hsl(var(--on-primary))",
        "primary-container": "hsl(var(--primary-container))",
        "on-primary-container": "hsl(var(--on-primary-container))",
        "primary-fixed": "hsl(var(--primary-fixed))",
        "primary-fixed-dim": "hsl(var(--primary-fixed-dim))",
        secondary: "hsl(var(--secondary))",
        "on-secondary": "hsl(var(--on-secondary))",
        "secondary-container": "hsl(var(--secondary-container))",
        tertiary: "hsl(var(--tertiary))",
        "on-tertiary": "hsl(var(--on-tertiary))",
        error: "hsl(var(--error))",
        "deep-emerald-dark": "hsl(var(--deep-emerald-dark))",
        "cyan-accent": "hsl(var(--cyan-accent))",
        "soft-purple": "hsl(var(--soft-purple))",
      },
      borderRadius: {
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
        "3xl": "calc(var(--radius) + 12px)",
      },
      boxShadow: {
        line: "inset 0 0 0 1px hsl(var(--border))",
        elevated: "0 20px 48px -32px rgba(13, 38, 28, 0.34)",
        /* Soft, low-opacity card shadows matching the Stitch references. */
        card: "0 1px 3px 0 rgba(16, 30, 26, 0.06), 0 1px 2px -1px rgba(16, 30, 26, 0.08)",
        "card-hover": "0 8px 24px -12px rgba(0, 82, 50, 0.25)",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        micro: ["11px", { lineHeight: "1.4" }],
        small: ["13px", { lineHeight: "1.5" }],
        body: ["14px", { lineHeight: "1.6" }],
        "heading-sm": ["16px", { lineHeight: "1.4", fontWeight: "600", letterSpacing: "-0.01em" }],
        "heading-lg": ["20px", { lineHeight: "1.3", fontWeight: "600", letterSpacing: "-0.01em" }],
        display: ["28px", { lineHeight: "1.2", fontWeight: "600", letterSpacing: "-0.01em" }],
      },
      transitionTimingFunction: {
        product: "cubic-bezier(0.2, 0.8, 0.2, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
