import {
  Braces,
  Building2,
  Calendar,
  Camera,
  Check,
  EyeOff,
  FileText,
  FileUp,
  Fingerprint,
  Grid3X3,
  Hash,
  Hexagon,
  Layers3,
  ListFilter,
  MapPin,
  MessageSquareText,
  MonitorSmartphone,
  QrCode,
  Repeat2,
  ScanLine,
  Search,
  Sigma,
  SlidersHorizontal,
  Spline,
  Star,
  Table2,
  Tags,
  Timer,
  Type,
  Users,
  Variable,
} from "lucide-react";

import { type FieldType } from "@/lib/forms";

/** Maps each response type to the lucide icon shown for it in the builder (palette, field rows,
 * settings header). Presentation metadata only — the canonical type capabilities live in the
 * field-type registry in "@/lib/forms". */
export const fieldTypeIcons: Record<FieldType, typeof Type> = {
  text: Type,
  textarea: MessageSquareText,
  number: Hash,
  decimal: Hash,
  currency: Hash,
  phone: Type,
  email: Type,
  url: Type,
  password: Type,
  select: ListFilter,
  dropdown: ListFilter,
  multiselect: ListFilter,
  radio: ListFilter,
  checkbox: Check,
  ranking: ListFilter,
  likert: SlidersHorizontal,
  matrix_single: Table2,
  matrix_multi: Table2,
  nps: Star,
  rating: Star,
  gps: MapPin,
  geolocation: MapPin,
  map: MapPin,
  geofence: MapPin,
  polygon: Hexagon,
  photo: Camera,
  image: Camera,
  signature: Type,
  barcode: Braces,
  qr: QrCode,
  audio: MonitorSmartphone,
  video: MonitorSmartphone,
  file: FileUp,
  date: Calendar,
  time: Calendar,
  datetime: Calendar,
  hidden: EyeOff,
  calculated: Sigma,
  repeat_group: Repeat2,
  grid: Grid3X3,
  lookup: Search,
  auto_id: Variable,
  month: Calendar,
  day_of_week: Calendar,
  path: Spline,
  pdf: FileText,
  scan_document: ScanLine,
  fingerprint: Fingerprint,
  article: FileText,
  user_select: Users,
  org_select: Building2,
  subform: Layers3,
  percentage: Hash,
  yes_no: Check,
  counter: Hash,
  date_range: Calendar,
  measurement: SlidersHorizontal,
  constant_sum: SlidersHorizontal,
  slider: SlidersHorizontal,
  range: SlidersHorizontal,
  duration: Timer,
  tags: Tags,
  timestamp: Timer,
};
