export const canonicalRoutes = {
  dashboard: ["/dashboard"],
  projects: [
    "/projects",
    "/projects/all",
    "/projects/active",
    "/projects/draft",
    "/projects/closed",
    "/projects/templates",
    "/projects/:projectId/overview",
    "/projects/:projectId/beneficiaries",
    "/projects/:projectId/data-import",
    "/projects/:projectId/forms",
    "/projects/:projectId/indicators",
    "/projects/:projectId/locations",
    "/projects/:projectId/teams",
    "/projects/:projectId/assignments",
    "/projects/:projectId/submissions",
    "/projects/:projectId/reports",
    "/projects/:projectId/settings",
    "/projects/:projectId/audit-trail",
  ],
  forms: [
    "/forms",
    "/forms/all",
    "/forms/draft",
    "/forms/published",
    "/forms/archived",
    "/forms/templates",
    "/forms/reference-data",
    "/forms/:formId/overview",
    "/forms/:formId/questions",
    "/forms/:formId/reference-data",
    "/forms/:formId/permissions",
    "/forms/:formId/workflow",
    "/forms/:formId/data-quality",
    "/forms/:formId/governance",
    "/forms/:formId/mapping-settings",
    "/forms/:formId/version-history",
    "/forms/:formId/audit-trail",
  ],
  fieldOperations: [
    "/field-operations",
    "/field-operations/assignments",
    "/field-operations/field-officers",
    "/field-operations/supervisors",
    "/field-operations/work-plans",
    "/field-operations/targets",
    "/field-operations/field-monitoring",
  ],
  submissions: [
    "/submissions",
    "/submissions/all",
    "/submissions/pending-review",
    "/submissions/approved",
    "/submissions/rejected",
    "/submissions/returned",
    "/submissions/archived",
  ],
  beneficiaries: [
    "/beneficiaries",
    "/beneficiaries/import",
    "/beneficiaries/duplicates",
    "/beneficiaries/:entityId",
  ],
  mapping: [
    "/mapping",
    "/mapping/project-maps",
    "/mapping/submission-maps",
    "/mapping/beneficiary-maps",
    "/mapping/facility-maps",
    "/mapping/coverage-maps",
    "/mapping/indicator-maps",
    "/mapping/data-quality-maps",
    "/mapping/layers",
    "/mapping/boundaries",
  ],
  indicators: [
    "/indicators",
    "/indicators/library",
    "/indicators/results-framework",
    "/indicators/logframes",
    "/indicators/targets",
    "/indicators/baselines",
    "/indicators/reports",
  ],
  reports: [
    "/reports",
    "/reports/standard",
    "/reports/custom",
    "/reports/dashboards",
    "/reports/scheduled",
    "/reports/exports",
  ],
  dataQuality: [
    "/data-quality",
    "/data-quality/dashboard",
    "/data-quality/duplicates",
    "/data-quality/outliers",
    "/data-quality/gps-issues",
    "/data-quality/missing-data",
    "/data-quality/validation-failures",
    "/data-quality/risk-alerts",
    "/data-quality/rules",
  ],
  usersTeams: [
    "/users-teams",
    "/users-teams/users",
    "/users-teams/roles",
    "/users-teams/teams",
    "/users-teams/organizations",
    "/users-teams/permissions",
    "/users-teams/activity-logs",
  ],
  governance: [
    "/governance",
    "/governance/audit-trail",
    "/governance/policies",
    "/governance/approvals",
    "/governance/retention-rules",
    "/governance/consent-management",
    "/governance/compliance",
    "/governance/data-stewardship",
  ],
  administration: [
    "/administration",
    "/administration/location-hierarchy",
    "/administration/reference-data",
    "/administration/notification-settings",
    "/administration/api-settings",
    "/administration/integrations",
    "/administration/system-settings",
    "/administration/backup-recovery",
    "/administration/imports-migration",
    "/administration/mobile-devices",
    "/administration/mobile-devices/:deviceId",
    "/administration/mobile-versions",
    "/administration/mobile-pilots",
    "/administration/mobile-monitoring",
    "/administration/mobile-monitoring/crashes",
    "/administration/mobile-feedback",
    "/administration/mobile-testing",
  ],
} as const;

export type CanonicalRouteModule = keyof typeof canonicalRoutes;
