import type {
  AccessCatalog,
  OrganizationGovernanceSummary,
  OrganizationUnitRead,
  RoleRead,
  SessionLogRead,
  TeamRead,
  UserRead,
  UsersTeamsActivityLogRead,
  UsersTeamsSummaryRead,
  WorkforceProfileRead,
} from "@/lib/api";

export const usersTeamsSections = [
  { id: "dashboard", label: "Overview" },
  { id: "users", label: "Users" },
  { id: "roles", label: "Roles" },
  { id: "teams", label: "Teams" },
  { id: "organizations", label: "Organizations" },
  { id: "permissions", label: "Permissions" },
  { id: "activity-logs", label: "Activity Logs" },
] as const;

export type UsersTeamsSection = (typeof usersTeamsSections)[number]["id"];

export const previewUsers: UserRead[] = [
  {
    email: "amina.okoro@atlas-demo.org",
    full_name: "Amina Okoro",
    geography_id: "north-region",
    id: "user-amina",
    is_active: true,
    login_slug: "atlas",
    organization_unit_id: "unit-national",
    project_id: "food-security",
    role_name: "M&E Manager",
    scope_type: "organization",
  },
  {
    email: "daniel.musa@atlas-demo.org",
    full_name: "Daniel Musa",
    geography_id: "district-a",
    id: "user-daniel",
    is_active: true,
    login_slug: "atlas",
    organization_unit_id: "unit-regional",
    project_id: "food-security",
    role_name: "Supervisor",
    scope_type: "district",
  },
  {
    email: "grace.field@atlas-demo.org",
    full_name: "Grace Field",
    geography_id: "community-12",
    id: "user-grace",
    is_active: true,
    login_slug: "atlas",
    organization_unit_id: "unit-district",
    project_id: "food-security",
    role_name: "Field Officer",
    scope_type: "own",
  },
  {
    email: "observer@donor.org",
    full_name: "Donor Observer",
    geography_id: null,
    id: "user-donor",
    is_active: false,
    login_slug: "atlas",
    organization_unit_id: null,
    project_id: null,
    role_name: "Viewer/Donor",
    scope_type: "organization",
  },
];

export const previewRoles: RoleRead[] = [
  {
    description: "Owns tenant configuration, users, roles, and organization data.",
    id: "role-owner",
    is_system: true,
    label: "Organization Owner",
    name: "organization_owner",
    organization_id: "org-preview",
    permissions: ["users.view", "users.create", "users.manage", "roles.view", "roles.manage", "organization.read", "data.import", "data.bulk_edit"],
    scope_type: "organization",
  },
  {
    description: "Manages projects, forms, field teams, review queues, and reports.",
    id: "role-me",
    is_system: true,
    label: "M&E Manager",
    name: "regional_manager",
    organization_id: "org-preview",
    permissions: ["users.view", "users.create", "roles.view", "forms.view", "submissions.review", "reports.view", "data.import", "data.bulk_edit"],
    scope_type: "region",
  },
  {
    description: "Collects assigned survey forms and views own submissions.",
    id: "role-field",
    is_system: true,
    label: "Field Officer",
    name: "field_officer",
    organization_id: "org-preview",
    permissions: ["forms.view", "submissions.create", "sync.mobile"],
    scope_type: "own",
  },
];

export const previewTeams: TeamRead[] = [
  {
    code: "SURVEY-A",
    created_at: new Date().toISOString(),
    department_id: null,
    id: "team-survey-a",
    is_active: true,
    manager_user_id: "user-daniel",
    name: "Survey Team A",
    organization_unit_id: "unit-district",
    project_id: "food-security",
    region: "North Region",
    team_type: "field_team",
  },
  {
    code: "DQ-01",
    created_at: new Date().toISOString(),
    department_id: null,
    id: "team-dq",
    is_active: true,
    manager_user_id: "user-amina",
    name: "Data Quality Team",
    organization_unit_id: "unit-national",
    project_id: null,
    region: "National",
    team_type: "data_quality",
  },
];

export const previewUnits: OrganizationUnitRead[] = [
  {
    code: "HQ",
    id: "unit-national",
    name: "Head Office",
    organization_id: "org-preview",
    parent_unit_id: null,
    region: "National",
    unit_type: "Head Office",
  },
  {
    code: "NORTH",
    id: "unit-regional",
    name: "North Regional Office",
    organization_id: "org-preview",
    parent_unit_id: "unit-national",
    region: "North Region",
    unit_type: "Regional Office",
  },
  {
    code: "DIST-A",
    id: "unit-district",
    name: "District A Office",
    organization_id: "org-preview",
    parent_unit_id: "unit-regional",
    region: "District A",
    unit_type: "District Office",
  },
];

export const previewProfiles: WorkforceProfileRead[] = [
  {
    clearance_level: "standard",
    created_at: new Date().toISOString(),
    department_id: null,
    employee_code: "MNE-001",
    id: "profile-amina",
    job_title: "M&E Manager",
    lifecycle_status: "active",
    performance_score: 92,
    supervisor_user_id: null,
    team_id: "team-dq",
    user_id: "user-amina",
  },
  {
    clearance_level: "field",
    created_at: new Date().toISOString(),
    department_id: null,
    employee_code: "SUP-014",
    id: "profile-daniel",
    job_title: "Regional Supervisor",
    lifecycle_status: "active",
    performance_score: 87,
    supervisor_user_id: "user-amina",
    team_id: "team-survey-a",
    user_id: "user-daniel",
  },
  {
    clearance_level: "field",
    created_at: new Date().toISOString(),
    department_id: null,
    employee_code: "FO-207",
    id: "profile-grace",
    job_title: "Enumerator",
    lifecycle_status: "active",
    performance_score: 79,
    supervisor_user_id: "user-daniel",
    team_id: "team-survey-a",
    user_id: "user-grace",
  },
];

export const previewSessions: SessionLogRead[] = [
  {
    created_at: new Date().toISOString(),
    device_id: "android-grace",
    ended_at: null,
    id: "session-1",
    ip_address: "197.210.2.10",
    location_hint: "District A",
    risk_score: 0.12,
    status: "active",
    user_id: "user-grace",
  },
];

export const previewAccessCatalog: AccessCatalog = {
  permissions: [
    { group: "users", key: "users.view", label: "View Users" },
    { group: "users", key: "users.create", label: "Create Users" },
    { group: "users", key: "users.manage", label: "Manage Users" },
    { group: "roles", key: "roles.view", label: "View Roles" },
    { group: "roles", key: "roles.manage", label: "Manage Roles" },
    { group: "forms", key: "forms.publish", label: "Publish Forms" },
    { group: "submissions", key: "submissions.approve", label: "Approve Submissions" },
    { group: "reports", key: "reports.export", label: "Export Reports" },
  ],
  roles: [],
  scope_types: ["global", "organization", "region", "district", "field_team", "project", "own"],
  workflow_actions: ["submit", "review", "approve_district", "approve_regional", "export"],
};

export const previewSummary: UsersTeamsSummaryRead = {
  access_health_score: 88,
  active_sessions: 1,
  active_users: 3,
  high_risk_sessions: 0,
  inactive_users: 1,
  locked_accounts: 0,
  organizations: 1,
  pending_access_requests: 1,
  pending_invitations: 2,
  permission_alerts: 1,
  recent_activity: 4,
  roles: 3,
  suspended_users: 0,
  teams: 2,
  total_users: 4,
};

export const previewOrganizationSummary: OrganizationGovernanceSummary = {
  active_delegations: 0,
  active_sessions: 1,
  approval_matrices: 2,
  attention_items: ["One access request is waiting for manager review."],
  clearance_levels: 3,
  departments: 2,
  devices: 5,
  governance_score: 82,
  high_risk_sessions: 0,
  pending_access_requests: 1,
  teams: 2,
  workforce_profiles: 3,
};

export const previewActivityLogs: UsersTeamsActivityLogRead[] = [
  {
    action: "identity.user_created",
    created_at: new Date().toISOString(),
    id: "activity-1",
    metadata: { status: "recorded" },
    resource_id: "user-grace",
    resource_type: "user",
    status: "recorded",
    user_id: "user-amina",
    user_label: "Amina Okoro",
  },
  {
    action: "org_governance.team_created",
    created_at: new Date(Date.now() - 3600 * 1000).toISOString(),
    id: "activity-2",
    metadata: { code: "SURVEY-A" },
    resource_id: "team-survey-a",
    resource_type: "operational_team",
    status: "recorded",
    user_id: "user-amina",
    user_label: "Amina Okoro",
  },
];
